name: Code quality check
run-name: Check code quality with linter
on: [push]
jobs:
    Linters:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: 'temurin'
                  java-version: 17

            - name: Set execute permissions for gradlew
              run: chmod +x gradlew

            - name: Detekt
              run: ./gradlew detekt

            - name: Public detekt reports
              uses: jwgmeligmeyling/checkstyle-github-action@master
              with:
                  path: '**/detekt.xml'
